# Mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/todolist
spring.datasource.username=root
spring.datasource.password=123456
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:todolist-schema.sql
spring.sql.init.data-locations=classpath:todolist-data.sql
spring.sql.init.continue-on-error=false

spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true